### ISSUE TITLE
Long menu do not adapt to small screens

### ISSUE THREAD

**Issue by sductor** [Martinomagnifico/reveal.js-simplemenu#2]
Hi, thank you for your work.
When I use the simplemenu in a window with a too small width, the last menu items are not displayed. Is there a way to dynamicly adapt font size in order for the menu to be always displayed, or to make the menu always been centered around the active item so that the next sections are alway displayed?

Sorry for my english

**Comment by sductor** [comment]
nailed it : in simplemenu.css, I put a compromised value for font size.
  font-size: 1.45vmin;
I tried the formula 
font-size: calc(1.2 * (0.5vmin + 0.5vmax));
https://stackoverflow.com/questions/26870217/css-fontsize-vmax-vmin-together-without-overwrite-responsive-text
but in the end it was better with really small values of vmax (0.01) so I just used vmin

**Comment by Martinomagnifico** [comment]
Hi Sylvain, thanks for using my plugin. It’s good that you found a solution. You might also try the CSS clamp function, which would be a good fit for your issue.

**Comment by sductor** [comment]
Thank you, it worked like a charm!
I put 0rem to allow it to work with page as small as possible
then my optimal configuration using vw and not vmin, since the menu is horizontal
then something like 1rem so that even in big screen, the size of the menu font remain reasonable.
