### ISSUE TITLE
[Bug] Incompatibility SimpleMenu and slideNumber option when exporting to PDF

### ISSUE THREAD

**Issue by maucejo** [Martinomagnifico/reveal.js-simplemenu#3]
Dear Martino,

First of all, thank you for this very useful plugin. As mentioned in the title, when the slideNumber option is activated in Reveal.initialize, the menu appears on all slides, even on those for which the menubar is hidden. 

**Step to reproduce the bug:** add "slideNumber: 'c'," in Reveal.initialize, e.g. in demo.html of the simplemenu repo.
**reveal.js version:** 4.3.1.

I suspect something in the pdf.scss of reveal distribution, but I don't know how to solve this issue.

Thank you for your help !

**Comment by Martinomagnifico** [comment]
Fixed in 1.1.2

**Comment by maucejo** [comment]
Top ! Thank you
