### ISSUE TITLE
Incompatibility with quarto

### ISSUE THREAD

**Issue by jwarz** [Martinomagnifico/reveal.js-simplemenu#4]
Dear Martino,

First of all, thank you for this very useful plugin. 

Unfortunately it does not work properly if I render my slides with quarto (reveal.js 4.3.1). It does not build a menubar. It only works with level 2 headings and therefore not with stacks.

This is generated html using vertical stacks (h1 and h2 headings):

```html
<section hidden="" aria-hidden="true" class="stack future" style="display: block;">
   <section id="in-the-morning" class="title-slide slide level1 center" data-name="In the morning" style="top: 224px; display: block;" data-pdf-page-number="1">
      <h1>In the morning</h1>
      <ul>
         <li>because it’s early</li>
         <li>there is no content….</li>
      </ul>
   </section>
   <section id="getting-up" class="slide level2 future" data-name="Getting Up" aria-hidden="true" data-pdf-page-number="2" style="display: block;">
      <h2>Getting up</h2>
      <ul>
         <li>Turn off alarm</li>
         <li>Get out of bed</li>
      </ul>
   </section>
   <section class="slide level2 future" aria-hidden="true" data-pdf-page-number="3" style="display: none;"></section>
</section>
```

Just using level 2 headings creates a menu:

```html
<section id="inthemorning" class="slide level2 present" data-name="In the morning" style="display: block;" data-pdf-page-number="1">
   <h2>In the morning</h2>
   <ul>
      <li>because it’s early</li>
      <li>there is no content….</li>
   </ul>
</section>
```

Does the simpleMenu function considers the extra `<section>` tag with the `stack` class?

**Comment by Martinomagnifico** [comment]
Hi Joschka,

Thanks for the compliment. It looks like Quarto adds another outer section (a stack) to your slides. Is that correct? Was it originally (the beasic markup before the rendering) only the inner 3 sections?

**Comment by jwarz** [comment]
> Was it originally (the beasic markup before the rendering) only the inner 3 sections?

The presentations are rendered from `.qmd` files:

Just using level 2 headings (creates a menubar):

```md
---
title: "SimpleMenu Example"
format:
  revealjs: 
    navigation-mode: grid
    chalkboard: true
revealjs-plugins:
  - simplemenu
---

## In the morning {data-name="In the morning"}

- because it's early
- there is no content....

## In the evening {data-name="In the evening"}

- Turn off alarm
- Get out of bed
```

Using stacks (does not create a menubar):

```md
---
title: "SimpleMenu Example"
format:
  revealjs: 
    navigation-mode: grid
    chalkboard: true
revealjs-plugins:
  - simplemenu
---

# In the morning {data-name="In the morning"}

---

## First slide {data-name="In the morning"}

- because it's early
- there is no content....

## Second slide {data-name="In the morning"}

- Turn off alarm
- Get out of bed

---
```

**Comment by Martinomagnifico** [comment]
It looks indeed like the stack is generated around the child slides, because of the heading levels being used. Apparently, whenever you use a 1st level heading anywhere, it will suppose that the user will want to create a vertical stack with the # being the title slide of that stack. You have no direct way of managing any attributes on that created stack, other than reverting to writing in HTML. Thinking in solutions: a _next version_ of Simplemenu can take the Quarto behaviour into account. Then you can do something like this:

```
---

# In the morning {data-stack-name="In the morning"}

## First slide

- because it's early
- there is no content....
```

**Comment by jwarz** [comment]
Ok, got it. Seems like a good approach. Do you happen to know which functions need to be reworked for this?

**Comment by Martinomagnifico** [comment]
Yep, tested it already. Go to your plugins folder and edit simplemenu.js:

There is this line at line 92: 

```
if (!isStack(section) && section.parentNode.tagName == "SECTION") {
    var parentAttributes = _toConsumableArray(section.parentNode.attributes);
    //...
```
change it to

```
if (!isStack(section) && section.parentNode.tagName == "SECTION") {
    if (!section.parentNode.dataset.name && section.dataset && section.dataset.stackName) {
        section.parentNode.dataset.name = section.dataset.stackName
    }
    var parentAttributes = _toConsumableArray(section.parentNode.attributes);
    //...
```

That will let the Markdown which I proposed above work. There is some other work to be done on the plugin, and I want to combine that so I can't push it yet, but this solution will work for now.

Let me know if it works.

**Comment by jwarz** [comment]
Great. Thanks a lot. Works like a charme. [Here](https://jwarz.github.io/quarto-revealjs-SimpleMenu) is a demo.

Because the level 2 headings are touching the menubar I have increased the inset: 

```css
.slides {
  inset: 55% auto auto 50% !important;
  transform: translate(-50%, -50%) scale(0.95);
}
```

Because it also affects the level 1 headings this is just a temporary fix (They are not centered anymore).

**Comment by Martinomagnifico** [comment]
Hi Joschka, you can adjust the ‘margin’ setting in the Reveal options for that.

**Comment by Martinomagnifico** [comment]
Hi Joschka, the plugin is now updated, and the Quarto version can be found at: [https://github.com/Martinomagnifico/quarto-simplemenu](https://github.com/Martinomagnifico/quarto-simplemenu)
