### ISSUE TITLE
sveltekit and vite issue with simplemenu.css

### ISSUE THREAD

**Issue by Kadalia** [Martinomagnifico/reveal.js-simplemenu#7]
Hello,

I was able tu run reveal.js in a sveltkit application.
But when I try to add your plugin, simplemenu.css is not found.
It works fine in dev mode, but when vite is used in production mode, all stuff is packaged ... and I get a 404 in the browser.
The problem is probably due to dynamic loading of simplemenu.css.
The other built-in plugins of reveal.js work fine, but no css is needed.

Do you have any idea ?

Bye the way great work ! Thank you
Philippe

**Comment by Martinomagnifico** [comment]
Hi Philippe, could you check the Multimodal plugin? It uses a somewhat different way for the CSS, and makes the loading of it configurable. It also has a `style` entry in package.json, which should make the usage of it automatic in bundlers. If that works for you in the Sveltekit app, then I’ll apply the same logic here in the next update.

**Comment by Kadalia** [comment]
Hi Martin,
I've found a way ! 
The idea is to import the css file. The "magic" then is ```csspath: false```

```
<script>
    ...
    import "reveal.js/dist/reveal.css";
    import "reveal.js/dist/theme/black.css";
    import "reveal.js/plugin/highlight/monokai.css";

    import Reveal from "reveal.js/dist/reveal.esm.js";
    import { onMount, tick } from "svelte";

    import Markdown from "reveal.js/plugin/markdown/markdown.esm.js";
    import RevealNotes from "reveal.js/plugin/notes/notes.esm.js";
    import RevealHighlight from "reveal.js/plugin/highlight/highlight.esm.js";

    import "reveal.js-simplemenu/plugin/simplemenu/simplemenu.css";
    import RevealSimplemenu from "reveal.js-simplemenu/plugin/simplemenu/simplemenu.esm.js";

    import 'reveal.js-verticator/plugin/verticator/verticator.css';
    import RevealVerticator from 'reveal.js-verticator/plugin/verticator/verticator.esm.js';

    export let reveal;

    onMount(async () => {
        await tick();
        const deck = new Reveal(reveal);
        deck.initialize({
            plugins: [Markdown, RevealNotes, RevealHighlight, RevealSimplemenu, RevealVerticator],
            slideNumber: 'c/t',
            simplemenu: {
                csspath: false,
            },
        });
    });
</script>
```

It works also with :

```
    import simplemenu from "reveal.js-simplemenu/plugin/simplemenu/simplemenu.css?url";
...
    csspath: simplemenu,
...
```

Nice :-)

I'll give a try with your method.

Thank you !

**Comment by Kadalia** [comment]
Just realized now that it's clearly explained in the documentation ... RTM ? RTFM !!
(verticator's documentation is crystal clear about csspath behavior ... simplemenu ... a little bit less ... but my bad anyway)
Sorry to bother.
